# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Push to DI

on:
  push
  #workflow_dispatch:
jobs:
 
  build:

    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
        DAYS: ${{ DAYS }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
   # - name: Use Node.js ${{ matrix.node-version }}
   #   uses: actions/setup-node@v4
   #   with:
   #     node-version: ${{ matrix.node-version }}
   #    cache: 'npm'
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test
#    - run: git version
#    - run: git log
    - run: gh version
    - run: gh api repos/demouser2002/demoNodeJSApp/issues
    - run: sh script.sh
    - run: cat commits.json
    - run: sh pushIssues.sh $DAYS
    - run: cat issues.json
