# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Push to DI

on:
  push
  #workflow_dispatch:
jobs:
 
  build:

    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
        
    steps:
    - uses: actions/checkout@v4
    - run: sh pushToDI.sh start_date=2025-02-10 end_date=2025-04-01 issues=true commits=true pullrequests=true
